Checks, cleanup, remove unneeded prints

diff --git a/batchdl b/batchdl
--- a/batchdl
+++ b/batchdl
@@ -9,18 +9,26 @@
 # with -b start-time and -e end-time being optional for downloading only part of the vod
 
 # Debug
-# set -x
+#set -x
 
 VODFILE=$1
+if [ -z "$1" ]
+then
+	printf "Missing input file.\nUsage: ./batchdl <input-file>\n"
+	exit 1
+fi
+
 SCRIPT="twitchvods"
 
 printf "Reading from file: $VODFILE\n"
 
+# Check input file exists
 if [ ! -f "$VODFILE" ]; then
 	printf "Error: $VODFILE not found.\n"
 	exit 1
 fi
 
+# Loop through the input file
 while IFS= read -r line; do
 	if [ -z "$line" ]; then
 		continue
diff --git a/twitchvods b/twitchvods
--- a/twitchvods
+++ b/twitchvods
@@ -1,10 +1,5 @@
 #!/usr/bin/bash
-#if [ -z "$2" ]
-#then
-#	echo "Usage: ./twitchvods.sh <vod-url or vod-id> <vod-name>"
-#	exit 1
-#fi
-
+set -e
 # Flags
 # -i vod-id
 # -o output-file
@@ -29,8 +24,8 @@ while getopts "i:o:b:e:h" flag; do
 			VOD_E="-e $OPTARG"
 			;;
 		h)
-			printf "Usage: $0 [-i VOD-id] [-o output-name] [-b start_time] [-e end_time]\n"
-			printf "Example (start 10 minutes in, end at 20 minutes): \n./twitchvods -i 2698747726 -o test-vod -b 600 -e 1200\n"
+			printf "Usage: $0 [-i VOD-id] [-o output-name] [-b begin_time] [-e end_time]\n"
+			printf "Example (start 10 minutes in, end at 20 minutes): \n./twitchvods -i 2698747726 -o test-vod -b 10m -e 20m\n"
 			printf "Example (entire vod): \n./twitchvods -i 2698747726 -o testvod\n"
 			exit 1
 			;;
@@ -39,9 +34,22 @@ done
 
 shift $((OPTIND-1))
 
-printf "VODID: $VOD\nOutput file: $FILENAME\nStart time: $VOD_B\nEnd time: $VOD_E\n"
+for arg in VOD FILENAME; do
+	if [[ -z "${!arg}" ]]; then
+		printf "Missing required argument for ${arg@Q}\n"
+		printf "./twitchvods -h for usage info\n"
+		exit 1
+	fi
+done
+
+printf "VOD ID: $VOD\nOutput file: $FILENAME\nBegin time: $VOD_B\nEnd time: $VOD_E\n"
 
 printf "Let's make some Twitch vods with chat overlay!\n"
+
+# Output directory
+# Default current directory (TwitchDownloaderCLI)
+# NOT IMPLEMENTED
+# VOD_DIR="."
 
 # Video download settings
 # Trim mode, Safe / Exact (Default)
@@ -75,16 +83,12 @@ CHAT_FONT_SIZE=18
 # Chat badges, default false
 CHAT_BADGES="false"
 
-
-
 # FFmpeg settings
-# preset, default medium
+# ffmpeg preset, default medium
 FFMPEG_PRESET='medium'
-# crf value, 0-51, 0 being lossless and 51 most compressed (worst quality)
-# default 23
+# crf value, 0-51, 0 being lossless and 51 most compressed (worst quality), default 23
 FFMPEG_CRF=23
-# Output resolution
-# Default 1920x1080
+# Output resolution, Default 1920x1080
 OUT_RES="1920x1080"
 
 
@@ -96,17 +100,16 @@ printf "Starting chat download for $FILENAME\n"
 ./TwitchDownloaderCLI chatdownload --id $VOD $VOD_B $VOD_E -o $FILENAME/$FILENAME-chat.json
 printf "VOD chat downloaded for $FILENAME\n"
 
-printf "Starting VOD chat render for $FILENAME\n"
+printf "Rendering VOD chat to mp4 for $FILENAME\n"
 ./TwitchDownloaderCLI chatrender -i $FILENAME/$FILENAME-chat.json -h $CHAT_HEIGHT -w $CHAT_WIDTH --framerate $CHAT_FPS --update-rate $CHAT_UPD_RATE --font-size $CHAT_FONT_SIZE --badges=$CHAT_BADGES -o $FILENAME/$FILENAME-chat.mp4 &
-printf "Chat rendered for $FILENAME\n"
 
 printf "Starting vod download for $FILENAME\n"
 ./TwitchDownloaderCLI videodownload --id $VOD $VOD_B $VOD_E --trim-mode=$VOD_DL_TRIM --threads=$VOD_DL_THREADS --bandwidth=$VOD_DL_BWIDTH -o $FILENAME/$FILENAME-vod.mp4 &
-printf "Vod download finished.\n"
 
 wait
+printf "Chat rendered and vod downloaded.\n"
 
-printf "FFmpgeg render starting...\n"
+printf "Overlaying the vod with the chat with ffmpeg...\n"
 ffmpeg -i $FILENAME/$FILENAME-vod.mp4 -i $FILENAME/$FILENAME-chat.mp4 -filter_complex "[0:v]scale=$OUT_RES[scaled];[1:v]colorkey=0x111111:0.01:0.1[ckout];[scaled][ckout]overlay=$CHAT_POS_X:$CHAT_POS_Y:format=auto[out]" -map "[out]" -map 0:a -c:v libx264 -preset $FFMPEG_PRESET -crf $FFMPEG_CRF -c:a copy $FILENAME/$FILENAME.mp4
 
 printf "Video render done! Finished file: $FILENAME/$FILENAME.mp4\n"
